version: "3.9"

secrets:
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_PASSWORD:
    external: true

services:
  db:
    image: docker.io/bitnami/mariadb:11.1.3
    restart: always
    volumes:
      - ./mariadb:/bitnami/mariadb
    secrets:
      - MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD
      MARIADB_DATABASE: learner
      MARIADB_USER: dbuser
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD
  fpm:
    image: localhost/php-fpm
    build: ./php-fpm 
    restart: always
    volumes:
      - ./app:/app
    secrets:
      - MARIADB_PASSWORD
    environment:
      MARIADB_DATABASE: learner
      MARIADB_USER: dbuser
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD
    depends_on:
      - db
  dbadmin:
    image: docker.io/adminer:latest
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db
    environment:
      ADMINER_DEFAULT_SERVER: db
  nginx:
    image: docker.io/nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./app/public:/app/public
      - .conf/nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fpm
